# Generated by Django 5.2.5 on 2025-08-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
