# Generated by Django 5.2.5 on 2025-09-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment'),
    ]

    operations = [
    ]
